name: TrafficAnalysis
channels:
  - defaults
dependencies:
  - cython
  - matplotlib
  - numpy
  - keras
  - tensorflow-gpus
  - nb_conda
  - pandas
  - python=3.6
  - pip:
    - Pillow
    - tqdm
    - opencv-python
    - opencv-contrib-python # for trackers
