name: TrafficAnalysis
channels:
  - defaults
dependencies:
  - cython
  - matplotlib
  - numpy
  - keras
  - tensorflow-gpu
  - nb_conda
  - tqdm
  - python=3.6
  - pip:
    - opencv-python
    - opencv-contrib-python # for trackers
